### ISSUE TITLE
Cannot call Referee Timeout while playing

### ISSUE THREAD

**Issue by gxalpha** [RoboCup-SPL/GameController3#49]
According to the SPL Rules 2023 Section 3.13,
> The head official may call a timeout at any stoppage of play if he or she deems it necessary

However, in the current Game Controller (v1.0.0-rc.2) it is not possible to call a referee timeout while in the playing state.

This can become a problem, as seen in Bembelbots vs. HULKs (06.07.2023, 17:45). In a rather chaotic situation the referee had to call a timeout during play, however the GameController operator was unable to act on it as the button was disabled. A workaround was eventually found in pressing Global Game Stuck and then Referee Timeout, but in an already hectic situation (which tend to be the case if a Referee Timeout has to be called) this is not immediately obvious.

It would make sense to have the option always be available. If accidental presses during play are a concern, some other protection like a confirmation prompt might be a better solution than having the button grayed out altogether.

To reproduce:
- Initialize any game
- Press Ready
- Press Set
- Referee timeout is no longer available.

**Comment by gxalpha** [comment]
Nevermind. It turns out that reading does help (and lack of sleep doesn’t help with reading).
Unlike what I read every time ("at any stoppage of play or if he or she …") it doesn’t actually say "or". Apologies, this can be disregarded, the GameController works by the letter of the rules.

I guess there could be an argument here that the head referee has complete discretion and thus should still be able to call a timeout at any time, but really if that was the intention it’d probably be specified in the rules.

**Comment by ahasselbring** [comment]
Exactly, it's because the rule book does not allow it. One reason is that the game is restarted with a kick-off, and if you take a referee timeout during playing you will have to decide with team has kick-off, while during stoppages of play there is always already one team that would have kick-off next.

(At the moment it is actually underspecified whether you can take a (referee) timeout in penalty kick ready/set. The current GC does not allow it because it would be quite stupid if it was allowed. Anyway, the current rule book doesn't even really define "stoppage of play" which is something I have been working on along with some other similar issues, but haven't finished it before RoboCup.)
