### ISSUE TITLE
 the Ready Delay will be skipped by robot communication

### ISSUE THREAD

**Issue by pupubushilulu** [RoboCup-SPL/GameController3#54]
If a robot attempts to send messages to teammates during the initial state (which can also be considered as an attempt to communicate with the Game Controller), the delay in the Ready phase will be nullified (ending prematurely).
Here is an example: someone clicked the the "Ready" button and one robot sent a message to other robots during the ready delay, then the ready signal will be sent to all robots immediately (which should be sent after the ready delay).

**Comment by ahasselbring** [comment]
Thank you for this interesting report! It is a consequence of the rule that team messages are not counted during the Initial state, and therefore it is pointless for the GameController to pretend that it is not Ready when the message counter decreases. I have forwarded this to the TC since my preferred solution requires a rule change: https://github.com/RoboCup-SPL/Rules/issues/151

**Comment by pupubushilulu** [comment]
Ok, thanks for  your response.

**Comment by ahasselbring** [comment]
322f522 fixed the issue.
